### ISSUE TITLE
Please remove references to old name 'ngx-qrcode2'

### ISSUE THREAD

**Issue by mautematico** [techiediaries/ngx-qrcode#10]
Hola, by some reason, when I use your '@techiediaries/ngx-qrcode' on a new ng-cli app, it works just well on dev environment, but it crashes the app build stage if I try to use it on prod.

The error is shown as follows by CI tool:

`
ERROR in /opt/build/repo/src/$$_gendir/node_modules/@techiediaries/ngx-qrcode/ngx-qrcode2.ngfactory.ts (10,21): Cannot find module 'ngx-qrcode2'.
ERROR in /opt/build/repo/src/$$_gendir/app/app.module.ngfactory.ts (66,22): Cannot find module 'ngx-qrcode2'.
`

Which for me indicates that the version 0.0.5 published on npm still has references to old 'ngx-qrcode2'.

By instance, I was able to find this tree references:

package.json:
`
  "module": "ngx-qrcode2.js",
  "name": "@techiediaries/ngx-qrcode",
...
  "typings": "ngx-qrcode2.d.ts",
`

ngx-qrcode2.metadata.json
`
    "importAs": "ngx-qrcode2"
`

and of course those two file names:
ngx-qrcode2.metadata.json
ngx-qrcode2.d.ts

Hope it helps to find and fix the wrong reference that is crashing prod builds.

¡Gracias por tu buen trabajo!

**Comment by techiediaries** [comment]
hi,

You can for now install ngx-qrcode2 

`npm install ngx-qrcode`

Instead of 

`npm install @techiediaries/ngx-qrcode`

Until that is fixed

**Comment by mautematico** [comment]
Yep, that's what I'm doing at the moment.

Gracias.

**Comment by yurik94** [comment]
same error here on Ionic 3.7.1 in --prod mode

**Comment by mautematico** [comment]
>same error here on Ionic 3.7.1 in --prod mode
It is because ionic uses @angular/cli under the hood. Same steps will fix your issue until permanent solution comes:

https://github.com/techiediaries/ngx-qrcode/issues/10#issuecomment-331145562

**Comment by yurik94** [comment]
Yup I know, already fixed thanks, just sharing for other people 😄

**Comment by bergamin** [comment]
@techiediaries is this really fixed? I'm still seeing this error. As the comment from 2017 says, the deprecated package works fine. This one doesn't.

**Comment by rafa-as** [comment]
@bergamin please, open a new issue. We are working to solve another related issue.

**Comment by shripatki** [comment]
still getting the error please work

**Comment by Cambrion** [comment]
Yeah, getting the same error after running `ng build --prod`

**Comment by rafa-as** [comment]
@Cambrion please, check the new 9.1.0 version

**Comment by manolo07** [comment]
Yes in fact typing:
```console
npm uninstall @techiediaries/ngx-qrcode --save && npm install @techiediaries/ngx-qrcode && ng build --prod
```
Upgrades version and compiles.
