### ISSUE TITLE
QR Code not showing up in IE 11 (Version 11.0.9600.18697CO)

### ISSUE THREAD

**Issue by hiddencaliber** [techiediaries/ngx-qrcode#2]
Hi,

I adjusted the polyfills for IE and tried running this app.
The QR Code shows perfectly in Chrome, Firefox and Safari but not in IE11.

Please let me know if there is any external file needed to make it work in IE11.

Thanks.

**Comment by techiediaries** [comment]
Did you try to change the output mode to canvas: 
`
<ngx-qrcode [qrc-value]="value"  [qrc-element-type]="canvas"></ngx-qrcode>  
`

**Comment by hiddencaliber** [comment]
Yes, I have the same implementation but still same problem is there
