### ISSUE TITLE
Can't bind to 'qrc-value' since it isn't a known property of 'ngx-qrcode'.

### ISSUE THREAD

**Issue by juni381** [techiediaries/ngx-qrcode#20]
i have install the package with "npm install ngx-qrcode2 --save " and then successfully add the module into app.module.ts.. afterwards i used this package in my component . I am getting following error.. please help!! 

`Uncaught Error: Template parse errors:
Can't bind to 'qrc-value' since it isn't a known property of 'ngx-qrcode'.
1. If 'ngx-qrcode' is an Angular component and it has 'qrc-value' input, then verify that it is part of this module.
2. If 'ngx-qrcode' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  
  <ion-card *ngIf="createdCode">
    <ngx-qrcode [ERROR ->][qrc-value] = "createdCode"></ngx-qrcode>
    <ion-card-content>
      <p>Value: {{ createdCode }}</p"): ng:///QrscannerPageModule/QrscannerPage.html@29:16`

> i am also pasting the code  below

` createdCode  : null ; 
 qrData : null ;

encodeText(){
this.createdCode = this.qrData;
  }
`

**Comment by wangren988888** [comment]
Hello, I have the same problem. Have you solved this problem?

**Comment by Bramzor** [comment]
Same here +1

**Comment by Bramzor** [comment]
I ended up using this:  `<ngx-qrcode [(qrc-value)]="createdCode"></ngx-qrcode>` and that seems to be working perfectly. So should use [(qrc-value)] instead of [qrc-value]

**Comment by bahodirk** [comment]
If you are using lazy-loading, import NgxQRCodeModule on the module where is your page, not on app.module

**Comment by Bunny899** [comment]
> If you are using lazy-loading, import NgxQRCodeModule on the module where is your page, not on app.module

how to do?

**Comment by kapil303196** [comment]
> If you are using lazy-loading, import NgxQRCodeModule on the module where is your page, not on app.module

please explain

**Comment by asd456680** [comment]
in    **page.module.ts**   not in   app.module.ts

```
import { NgxQRCodeModule } from 'ngx-qrcode2';  //import this

@NgModule({
  imports: [
    ...
    NgxQRCodeModule     //add this
  ],
  declarations: [ ... ]
})
```

**Comment by manojbharti** [comment]
Not woking for me. I am using Ionic 5.0.7
