### ISSUE TITLE
Error: Unexpected module 'NgxQRCodeModule' declared by the module 'SharedModule'

### ISSUE THREAD

**Issue by mkgn** [techiediaries/ngx-qrcode#23]
I am using this from multiple modules. Therefore I have defined NgxQRCodeModule in a SharedModule that is accessible from all other modules.

However when i run; the console gives below error.

Error: Unexpected module 'NgxQRCodeModule' declared by the module 'SharedModule'. Please add a @Pipe/@Directive/@Component annotation.

Instead of importing NgxQRCodeModule, if i import the NgxQRCodeComponent it works. But then I can't compile the application in production mode (ng build --prod) since it complains about 2 declarations. See below.

ERROR in : Type NgxQRCodeComponent in E:/Projects/Forms/Main/src/xxx.Host/node_modules/ngx-qrcode2/ngx-qrcode2.d.ts is part of the declarations of 2 modules: SharedModule in E:/Projects/Forms/Main/src/xxx.Host/src/shared/shared.module.ts and NgxQRCodeModule in E:/Projects/Forms/Main/src/xxx.Host/node_modules/ngx-qrcode2/ngx-qrcode2.d.ts! 

What may be the problem?

**Comment by techiediaries** [comment]
Can you show the code of how you add **NgxQRCodeModule** to you shared module?

**Comment by mkgn** [comment]
Got it sorted. my blunder! Sorry for wasting a thread :(
