### ISSUE TITLE
Release to npm

### ISSUE THREAD

**Issue by rafa-as** [techiediaries/ngx-qrcode#29]
Please @techiediaries can you do the release to npm with the margin, width and the other new inputs?

**Comment by rafa-as** [comment]
Also upgrading from Angular 6 to 7

**Comment by sergiy-talashko** [comment]
@andrea-teom Can you release to npm your changes?

**Comment by andrea-teom** [comment]
https://www.npmjs.com/package/ngx-qrcode2-custom

Sergiy Talashko ha scritto il 16/01/19 alle 22:09:

**Comment by rafa-as** [comment]
@techiediaries can you provide me the NPM permissions to publish the library?

You can check the PR here https://github.com/techiediaries/ngx-qrcode/pull/43

My NPM user is: **rafa-as** https://www.npmjs.com/~rafa-as

Thank you!

**Comment by techiediaries** [comment]
I added you via Invite maintainer in the settings page but it's not working, can you publish to it or is there another way to give you publish access?

**Comment by rafa-as** [comment]
@techiediaries I have access to **@techiediaries/ngx-qrcode** instead of **ngx-qrcode2** . Where you want to have this library? Now it's on **ngx-qrcode2**.

If you want to move it to **@techiediaries/ngx-qrcode** some other changes should be performed.

Now the 9 version is publish on @techiediaries/ngx-qrcode do you want to remove/deprecate ng-qrcode2 or @techiediaries/ngx-qrcode ?

**Comment by techiediaries** [comment]
@rafa-as I added you to the maintainers of ngx-qrcode2 but I got this error 

Internal Service Error
id: c14c8d76-7769-42bb-9728-55cadc43ee95

Then I added you to the organization and it worked but Im not sure why you can't publish to ngx-qrcode2 because It also belongs to this org

**Comment by rafa-as** [comment]
I only can see
![Screenshot 2020-04-29 at 15 24 47](https://user-images.githubusercontent.com/594574/80601154-bb5fca80-8a2d-11ea-84c1-35bc175beb95.png)

Maybe it's a good idea to move to **@techiediaries/ngx-qrcode**? I have stashed the changes to rename it

Anyway, I have access to other packages under organizations but just only to one package.

**Comment by techiediaries** [comment]
Ok we can move to @techiediaries/ngx-qrcode

**Comment by rafa-as** [comment]
@techiediaries I've got the same error granting permissions and it's when left blank the username field.

![Screenshot 2020-04-29 at 15 55 45](https://user-images.githubusercontent.com/594574/80610124-409cac80-8a39-11ea-86d6-a2c870e39d99.png)
![Screenshot 2020-04-29 at 15 52 41](https://user-images.githubusercontent.com/594574/80610133-44303380-8a39-11ea-88ae-3be2be34048b.png)

You must add the username

![Screenshot 2020-04-29 at 15 55 57](https://user-images.githubusercontent.com/594574/80610164-4db99b80-8a39-11ea-8f3f-9d5b40a15c44.png)


I think that move to @techiediaries/ngx-qrcode sounds good but we should do some things:

- [ ] [Deprecate](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#deprecating-an-entire-package) ngx-qrcode2 package and encouraging all the people to move to @techiediaries/ngx-qrcode
- [ ] Remove me of techiediaries organization and just add me to @techiediaries/ngx-qrcode, as I have described above
- [ ] Create the PR with moving the package and indicating it at README

**Comment by techiediaries** [comment]
@rafa-as of course I added the username but gives the same error, if you try with two accounts you'll see the error I tried with two accounts of mine and got the same error.

**Comment by rafa-as** [comment]
@techiediaries FYI from NPM Tech Support:

> You're welcome, Rafa!
> 
> We're working on an issue on the backend that's preventing you from being added, so I'll follow up once fixed.
> 
> Best,

I'll add more replies about it

**Comment by rafa-as** [comment]
Good news @techiediaries ! NPM has already fixed the error and now I have access to ngx-qrcode2. I just published the 9 version on ngx-qrcode2.

I am going to deprecate the ngx-qrcode and publish 9.0.1 version with all the ngx-qrcode references replaced by @techiediaries/ngx-qrcode .

**Comment by rafa-as** [comment]
The package is published now and we can close this issue.
