### ISSUE TITLE
how can we add more than one parameter and get the return in base64

### ISSUE THREAD

**Issue by nicoisz** [techiediaries/ngx-qrcode#30]
how can we add more than one parameter and get the return in base64

**Comment by ALEXOTANO** [comment]
@nicoisz After you assign the values (so the ngx-qcode starts generating the QR):
`
let times = 0;
var revisa= setInterval(() => {
				let canvas:HTMLCanvasElement = document.querySelector("canvas");
				times++;
				if (canvas) {
					let d = canvas.toDataURL("image/jpeg").toString();
					console.log('datos de QR: ', d);
					clearInterval(revisa);
				}
				if
				(veces===15){
					clearInterval(checkExist);
					console.log('Error: despues de 3 segundos no se pudo obtener el canvas..');
				}
			}, 10);`

**Comment by rafa-as** [comment]
Closed due inactivity
