### ISSUE TITLE
Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by UzairNoman** [techiediaries/ngx-qrcode#34]
I am trying to create a build release for deployment `ionic cordova build android --prod --release` and I am getting this error.
![image](https://user-images.githubusercontent.com/12785891/55689095-142f7180-599a-11e9-93da-1da7e20948a8.png)

Error encountered resolving symbol values statically. Could not resolve ngx-qrcode2 relative to <path_to_app>/src/app/app.module.ts.

My app.module.ts files :
![image](https://user-images.githubusercontent.com/12785891/55689114-5953a380-599a-11e9-9743-5f1dda7a9601.png)

**Comment by rafa-as** [comment]
Can you check the new version 9, please?

**Comment by rafa-as** [comment]
Closed due inactivity
