### ISSUE TITLE
Angular 8 with Ivy enabled

### ISSUE THREAD

**Issue by Ludevik** [techiediaries/ngx-qrcode#36]
Currently the `package.json` of ng-qrcode2 contains 

`"module": "ngx-qrcode2.js",` 

which leads to 

`ERROR in ENOENT: no such file or directory, open '<projectPath>/node_modules/ngx-qrcode2/ngx-qrcode2.js` 

when Ivy is enabled.

See [related angular issue](https://github.com/angular/angular/issues/30781).

**Comment by dodongphure** [comment]
Any progress on this? Thanks!

**Comment by rafa-as** [comment]
Closed by #43

If the error persists open a new issue
