### ISSUE TITLE
Demo: Social media buttons overlapping text & input

### ISSUE THREAD

**Issue by LukasMarx** [techiediaries/ngx-qrcode#4]
The text and input of the demo is overlapped by the social media bar. I also noticed a lot of errors in the console.
Im using Chrome Version 59.0.3071.115

![issue](https://user-images.githubusercontent.com/8080408/29004815-72450502-7ace-11e7-98ec-d3b26052f7d1.JPG)
![issue-console](https://user-images.githubusercontent.com/8080408/29004816-7547d9be-7ace-11e7-871b-e8a4927cbc88.JPG)

**Comment by techiediaries** [comment]
Sorry for that, the errors in the console are related to website scripts not the qrcode library itself.
