### ISSUE TITLE
Unhandled Promise rejection: Fetch error: 404 Not Found

### ISSUE THREAD

**Issue by al-mart** [techiediaries/ngx-qrcode#40]
Hey guys I am having these problem on ngx-qrcode2 Module import ...
`zone.js:672 Unhandled Promise rejection: Fetch error: 404 Not Found
  Instantiating http://localhost:3001/ts
  Loading ts
  Unable to load transpiler to transpile http://localhost:3001/node_modules/ngx-qrcode2/index.js
  Instantiating http://localhost:3001/node_modules/ngx-qrcode2/index.js
  Loading node_modules/ngx-qrcode2/index.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Fetch error: 404 Not Found`

Im using System js with this angular module, and i use this module in another angular app which is loading using webpack , i dont have any problems there , 

When i comment out QR Code Module everything normalizes ...

I had some sort of this issue when i have got this import
`
import { Observable } from 'rxjs';
`
and When i changed this to that error disapears.. Thank you in advance.
`import { Observable } from 'rxjs/Observable';
`

**Comment by rafa-as** [comment]
Can you check the new version 9, please?

**Comment by rafa-as** [comment]
Closed due inactivity
