### ISSUE TITLE
Ionic/Angular 9 Error: Component import throws Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by mc-perry** [techiediaries/ngx-qrcode#41]
Importing module into component:

```
import { NgxQRCodeModule } from 'ngx-qrcode2';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    QRCodePageRoutingModule,
    NgxQRCodeModule
  ],
  declarations: [QRCodePage]
})
```

Using element in html:
```
    <ngx-qrcode
      [qrc-element-type]="elementType"
      [qrc-value]="qrData"
    ></ngx-qrcode>
```

When navigating into the page, Angular throws the following error:
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (VM34 vendor.js:75080)
    at VM34 vendor.js:75098
    at Array.forEach (<anonymous>)
    at registerNgModuleType (VM34 vendor.js:75094)
    at new NgModuleFactory$1 (VM34 vendor.js:75238)
    at Compiler_compileModuleSync__POST_R3__ (VM34 vendor.js:79154)

I downgraded my Ionic project version to 8 and confirmed that this error is no longer happening, so I think it must be an issue with Angular 9.

**Comment by rafa-as** [comment]
@mc-perry can you check the new version 9 please?

**Comment by rafa-as** [comment]
Closed due inactivity
