### ISSUE TITLE
QR-code with is not reflecting provided in style

### ISSUE THREAD

**Issue by Abhinav-Mingwal** [techiediaries/ngx-qrcode#48]
<ngx-qrcode
*ngIf="qrCodeValue?.length > 0"
[qrc-value]="qrCodeValue"
qrc-class="aclass"
style="height: 200px;"
qrc-errorCorrectionLevel="M"
>
200px style not working

**Comment by Abhinav-Mingwal** [comment]
fixed it a nested Image tag was getting build inside the ngx-qrcode tag which needed the width

**Comment by rakeshbaral92** [comment]
> fixed it a nested Image tag was getting build inside the ngx-qrcode tag which needed the width

Any code reference please
