### ISSUE TITLE
QR-code with is not reflecting provided in style

### ISSUE THREAD

**Issue by Abhinav-Mingwal** [techiediaries/ngx-qrcode#49]
<ngx-qrcode
            *ngIf="qrCodeValue?.length > 0"
            [qrc-value]="qrCodeValue"
            qrc-class="aclass"
            style="height: 200px;"
            qrc-errorCorrectionLevel="M"
          >
</ngx-qrcode>

200px style not working

**Comment by rafa-as** [comment]
Duplicate #48
