### ISSUE TITLE
 This likely means that the library (@techiediaries/ngx-qrcode) which declares NgxQRCodeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.     

### ISSUE THREAD

**Issue by gibbsvjy007** [techiediaries/ngx-qrcode#51]
This likely means that the library (@techiediaries/ngx-qrcode) which declares NgxQRCodeModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
Getting the above error with latest angular

**Comment by rafa-as** [comment]
Please @gibbsvjy007 update to the latest 9.0.0 version, remove node_modules and install it another time.

The library works properly with Angular 9.
