### ISSUE TITLE
qrcode.component.d.ts has build errors

### ISSUE THREAD

**Issue by diegolaisocialcities** [techiediaries/ngx-qrcode#55]
Hi, 

I can't build my app with this plugin because I have errors on file "qrcode.component.d.ts", in particular with these two lines:

version: import("./qrcode.types").NgxQrcodeVersionType;
errorCorrectionLevel: import("./qrcode.types").NgxQrcodeErrorCorrectionLevels;

where propierties _NgxQrcodeVersionType_ and _NgxQrcodeErrorCorrectionLevels_ "does not exists on type '"./qrcode.types"'. "

Does anyone know how to fix this? 

Thanks in advance.

**Comment by rafa-as** [comment]
Which Angular version are you using? and which ngx-qrcode version?

**Comment by rafa-as** [comment]
@diegolaisocialcities we just published a new [9.1.0](https://github.com/techiediaries/ngx-qrcode/releases/tag/9.1.0) version. Can you check it?

**Comment by rafa-as** [comment]
Closed due inactivity

**Comment by pallavibiwal** [comment]
i am facing same issue, any success on this
