### ISSUE TITLE
Provide a size property to resize the qr code

### ISSUE THREAD

**Issue by tjbutz** [techiediaries/ngx-qrcode#6]

**Comment by techiediaries** [comment]
It gets resized automatically if it needs that

**Comment by nathanccleung** [comment]
can I resize the img for display purpose?

**Comment by techiediaries** [comment]
No it gets resized depending on the amount of data you are encoding but if you need to resize it just for display we'll make sure to add that?

**Comment by nathanccleung** [comment]
yes just for display, because the original image is quite small if the content is not long enough.

**Comment by mautematico** [comment]
@techiediaries if you can point me on the right path, I will try to start a PR to get this feature added.

**Comment by techiediaries** [comment]
Hi @mautematico  how? do u have any specific question? i.e is it about building the component or code?

**Comment by Dark-Midnight** [comment]
Hi @nathanccleung .
You can add global styles to the `styles.css` and use `qrc-class` to control the size.

**Comment by uzumakinaruto123** [comment]
@techiediaries  @Dark-Midnight On changing styles, the qr code looks blur if its size is increased. Any chance that `ngx-qrcode` can generate high resolution image?

**Comment by gerard2p** [comment]
An option to generate a High Resolution Image will be great.

**Comment by marcburkhardt** [comment]
@techiediaries Could you please reopen this issue? I ran into the same issue as @uzumakinaruto123 and I would very much appreciate it if you added a HighRes option as @gerard2p suggested.

**Comment by uzumakinaruto123** [comment]
@gerard2p  @marcburkhardt  If you still looking for an answer, I have found a hack.  Basically, more the length of data string `[qrc-value] = "data"` more is the size of QR code.  So temporarily you can add some redundant garbage in your data along with actual data. I am stringifying a JSON object as value.

**Comment by uzumakinaruto123** [comment]
Size also varies depending upon `qrc-version = "8"` ranging from 1 to 40.

**Comment by gerard2p** [comment]
@uzumakinaruto123 @marcburkhardt  I actually write a custom component and my app based on this so i could actually modify the parameters that are send to QRCode.toDataURL If anyone is interested I can make that component available to everyone.

**Comment by uzumakinaruto123** [comment]
@gerard2p would like to check it!

**Comment by ranjanakash166** [comment]
@gerard2p will like to check the compoenet.

**Comment by bibekananda-pradhan** [comment]
please share whats the work around you have done @gerard2p

**Comment by rdev-software** [comment]
Any update ? Changing size in CSS creates blurred image

**Comment by ouassimBenMosbah** [comment]
I am facing the same issue. Any workaround ?

**Comment by SukunaTheGoat** [comment]
Also trying to change the size, if possible without lowering the img quality, but no success so far. The work-around posted above with changing attributes for IMG in css isn't working for me. Help is appreciated.

**Comment by zulis** [comment]
To set width just add [width]="250"
